# Generated by Django 6.0.3 on 2026-03-22 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse', '0009_rd001_nullable_pool_reserves'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(help_text="Strategy identifier, e.g. 'u001_volume_spike_v1'.", max_length=100)),
                ('strategy_version', models.IntegerField()),
                ('run_label', models.CharField(blank=True, default='', help_text='Optional human-readable label for this run.', max_length=200)),
                ('data_start', models.DateTimeField(help_text='Start of the test window (inclusive).')),
                ('data_end', models.DateTimeField(help_text='End of the test window (inclusive).')),
                ('params_snapshot', models.JSONField(help_text='Frozen complete strategy config for reproducibility.')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('entities_tested', models.IntegerField(blank=True, help_text='Number of entities (assets) included in the backtest.', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['strategy_id', '-started_at'], name='idx_u001bt_strategy_started'), models.Index(fields=['-started_at'], name='idx_u001bt_started')],
            },
        ),
        migrations.CreateModel(
            name='U001BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_pnl', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('avg_pnl_per_trade', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('max_win', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('max_loss', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('win_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('max_drawdown_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('avg_hold_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('entities_traded', models.IntegerField(default=0)),
                ('entities_profitable', models.IntegerField(default=0)),
                ('extra_metrics', models.JSONField(blank=True, default=dict)),
                ('pnl_distribution', models.JSONField(blank=True, default=dict)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='strategy.u001backtestrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U001BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('entry_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('exit_price', models.DecimalField(decimal_places=18, max_digits=38)),
                ('entry_amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('entry_reason', models.JSONField(help_text='Which signals fired with their values at entry.')),
                ('exit_reason', models.CharField(choices=[('take_profit', 'Take Profit'), ('stop_loss', 'Stop Loss'), ('timeout', 'Timeout'), ('exit_signal', 'Exit Signal'), ('force_close', 'Force Close')], max_length=20)),
                ('pnl', models.DecimalField(decimal_places=18, max_digits=38)),
                ('roi_pct', models.DecimalField(decimal_places=6, max_digits=20)),
                ('hold_minutes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_trades', to='warehouse.migratedcoin', to_field='mint_address')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategy.u001backtestrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'coin'], name='idx_u001bttrade_run_coin')],
            },
        ),
    ]
