# Generated by Django 6.0.3 on 2026-03-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='u001backtestrun',
            name='sweep_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Groups runs from the same parameter sweep.', max_length=100),
        ),
    ]
