# Generated by Django 6.0.3 on 2026-03-09 22:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigratedCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_event', models.DateTimeField(blank=True, null=True)),
                ('membership_end', models.DateTimeField(blank=True, null=True)),
                ('mint_address', models.CharField(max_length=50, unique=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HolderSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total_holders', models.BigIntegerField(null=True)),
                ('net_holder_change', models.BigIntegerField(null=True)),
                ('holder_percent_change', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('acquired_via_swap', models.BigIntegerField(null=True)),
                ('acquired_via_transfer', models.BigIntegerField(null=True)),
                ('acquired_via_airdrop', models.BigIntegerField(null=True)),
                ('holders_in_whales', models.BigIntegerField(null=True)),
                ('holders_in_sharks', models.BigIntegerField(null=True)),
                ('holders_in_dolphins', models.BigIntegerField(null=True)),
                ('holders_in_fish', models.BigIntegerField(null=True)),
                ('holders_in_octopus', models.BigIntegerField(null=True)),
                ('holders_in_crabs', models.BigIntegerField(null=True)),
                ('holders_in_shrimps', models.BigIntegerField(null=True)),
                ('holders_out_whales', models.BigIntegerField(null=True)),
                ('holders_out_sharks', models.BigIntegerField(null=True)),
                ('holders_out_dolphins', models.BigIntegerField(null=True)),
                ('holders_out_fish', models.BigIntegerField(null=True)),
                ('holders_out_octopus', models.BigIntegerField(null=True)),
                ('holders_out_crabs', models.BigIntegerField(null=True)),
                ('holders_out_shrimps', models.BigIntegerField(null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_snapshots', to='warehouse.migratedcoin', to_field='mint_address')),
            ],
            options={
                'unique_together': {('coin', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='OHLCVCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=18, max_digits=38, null=True)),
                ('high_price', models.DecimalField(decimal_places=18, max_digits=38, null=True)),
                ('low_price', models.DecimalField(decimal_places=18, max_digits=38, null=True)),
                ('close_price', models.DecimalField(decimal_places=18, max_digits=38, null=True)),
                ('volume', models.DecimalField(decimal_places=18, max_digits=38, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_candles', to='warehouse.migratedcoin', to_field='mint_address')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('high_price__gte', models.F('low_price'))), name='ohlcv_high_gte_low'), models.CheckConstraint(condition=models.Q(('volume__gte', Decimal('0'))), name='ohlcv_volume_non_negative')],
                'unique_together': {('coin', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PoolMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_address', models.CharField(max_length=50)),
                ('dex', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_mappings', to='warehouse.migratedcoin', to_field='mint_address')),
            ],
            options={
                'unique_together': {('coin', 'pool_address')},
            },
        ),
        migrations.CreateModel(
            name='RawTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_transactions', to='warehouse.migratedcoin', to_field='mint_address')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='warehouse_r_timesta_0b9fc2_idx')],
            },
        ),
    ]
