# Generated by Django 6.0.3 on 2026-03-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdersnapshot',
            name='timestamp',
            field=models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.'),
        ),
        migrations.AlterField(
            model_name='migratedcoin',
            name='anchor_event',
            field=models.DateTimeField(blank=True, help_text='The reference point (T0) for this asset. Populated for event-driven universes. Null for calendar-driven universes.', null=True),
        ),
        migrations.AlterField(
            model_name='migratedcoin',
            name='membership_end',
            field=models.DateTimeField(blank=True, help_text='When this asset left the universe. Null = still a member.', null=True),
        ),
        migrations.AlterField(
            model_name='ohlcvcandle',
            name='timestamp',
            field=models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.'),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='timestamp',
            field=models.DateTimeField(help_text='Exact event time, UTC. PIT behavior depends on the declared AVAILABILITY_RULE.'),
        ),
        migrations.AddIndex(
            model_name='holdersnapshot',
            index=models.Index(fields=['timestamp'], name='warehouse_h_timesta_333e20_idx'),
        ),
        migrations.AddIndex(
            model_name='ohlcvcandle',
            index=models.Index(fields=['timestamp'], name='warehouse_o_timesta_5c6b2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ohlcvcandle',
            constraint=models.CheckConstraint(condition=models.Q(('open_price__isnull', True), ('low_price__isnull', True), ('high_price__isnull', True), models.Q(('open_price__gte', models.F('low_price')), ('open_price__lte', models.F('high_price'))), _connector='OR'), name='ohlcv_open_in_range'),
        ),
        migrations.AddConstraint(
            model_name='ohlcvcandle',
            constraint=models.CheckConstraint(condition=models.Q(('close_price__isnull', True), ('low_price__isnull', True), ('high_price__isnull', True), models.Q(('close_price__gte', models.F('low_price')), ('close_price__lte', models.F('high_price'))), _connector='OR'), name='ohlcv_close_in_range'),
        ),
    ]
