# Generated by Django 6.0.3 on 2026-03-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_holdersnapshot_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('steady_state', 'Steady State'), ('refill', 'Re-fill')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('coins_attempted', models.IntegerField(default=0)),
                ('coins_succeeded', models.IntegerField(default=0)),
                ('coins_failed', models.IntegerField(default=0)),
                ('cu_consumed', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-started_at'], name='idx_batch_started'), models.Index(fields=['pipeline_id', '-started_at'], name='idx_batch_pipeline_started')],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('steady_state', 'Steady State'), ('refill', 'Re-fill')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_expected', models.IntegerField(blank=True, null=True)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cu_consumed', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(blank=True, help_text='Parent batch. Null for manual one-off runs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='warehouse.pipelinebatchrun')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='warehouse.migratedcoin', to_field='mint_address')),
            ],
            options={
                'indexes': [models.Index(fields=['coin', 'layer_id', '-started_at'], name='idx_run_coin_layer'), models.Index(fields=['-started_at'], name='idx_run_started'), models.Index(fields=['status'], name='idx_run_status')],
            },
        ),
    ]
