# Generated by Django 6.0.3 on 2026-03-10 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_pipelinebatchrun_pipelinerun'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('steady_state', 'Steady State'), ('refill', 'Re-fill')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_expected', models.IntegerField(blank=True, null=True)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cu_consumed', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='pipelinerun',
            name='idx_run_coin_layer',
        ),
        migrations.RemoveIndex(
            model_name='pipelinerun',
            name='idx_run_started',
        ),
        migrations.RemoveIndex(
            model_name='pipelinerun',
            name='idx_run_status',
        ),
        migrations.AddField(
            model_name='u001pipelinerun',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Parent batch. Null for manual one-off runs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_runs', to='warehouse.pipelinebatchrun'),
        ),
        migrations.AddField(
            model_name='u001pipelinerun',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='warehouse.migratedcoin', to_field='mint_address'),
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='pipelinerun',
            name='coin',
        ),
        migrations.AddIndex(
            model_name='u001pipelinerun',
            index=models.Index(fields=['coin', 'layer_id', '-started_at'], name='idx_u001run_coin_layer'),
        ),
        migrations.AddIndex(
            model_name='u001pipelinerun',
            index=models.Index(fields=['-started_at'], name='idx_u001run_started'),
        ),
        migrations.AddIndex(
            model_name='u001pipelinerun',
            index=models.Index(fields=['status'], name='idx_u001run_status'),
        ),
        migrations.DeleteModel(
            name='PipelineRun',
        ),
    ]
