# Generated by Django 6.0.3 on 2026-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_u001pipelinerun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='migratedcoin',
            name='decimals',
            field=models.PositiveSmallIntegerField(blank=True, help_text='SPL token decimals (usually 6, but not always)', null=True),
        ),
        migrations.AddField(
            model_name='migratedcoin',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Token logo URL from Moralis', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='migratedcoin',
            name='name',
            field=models.CharField(blank=True, help_text='Token name from Moralis', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='migratedcoin',
            name='symbol',
            field=models.CharField(blank=True, help_text='Token symbol from Moralis', max_length=50, null=True),
        ),
    ]
