# Generated by Django 6.0.3 on 2026-03-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_migratedcoin_decimals_migratedcoin_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001PipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('partial', 'Partial'), ('window_complete', 'Window Complete'), ('error', 'Error')], default='not_started', max_length=20)),
                ('watermark', models.DateTimeField(blank=True, help_text='Cached watermark — latest timestamp in the feature layer table for this entity. Source of truth is the feature layer table itself. Updated after each successful run.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Error message from the last failed run. Null if last run succeeded.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_statuses', to='warehouse.migratedcoin', to_field='mint_address')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.u001pipelinerun')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='idx_u001status_status'), models.Index(fields=['layer_id', 'status'], name='idx_u001status_layer_status')],
                'unique_together': {('coin', 'layer_id')},
            },
        ),
    ]
