# Generated by Django 6.0.3 on 2026-03-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_u001pipelinestatus'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='holdersnapshot',
            name='warehouse_h_timesta_333e20_idx',
        ),
        migrations.RemoveIndex(
            model_name='ohlcvcandle',
            name='warehouse_o_timesta_5c6b2b_idx',
        ),
    ]
