# Generated by Django 6.0.3 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_holdersnapshot_warehouse_h_timesta_333e20_idx_and_more'),
    ]

    operations = [
        # ---------------------------------------------------------------
        # RawTransaction: add 12 new fields
        # ---------------------------------------------------------------
        migrations.AddField(
            model_name='rawtransaction',
            name='tx_signature',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='wallet_address',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='token_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='sol_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='pool_address',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='tx_fee',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=38),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='lp_fee',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='protocol_fee',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='coin_creator_fee',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='pool_token_reserves',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawtransaction',
            name='pool_sol_reserves',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        # ---------------------------------------------------------------
        # RawTransaction: remove old timestamp-only index, add new indexes
        # ---------------------------------------------------------------
        migrations.RemoveIndex(
            model_name='rawtransaction',
            name='warehouse_r_timesta_0b9fc2_idx',
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['coin', 'timestamp'], name='warehouse_r_coin_id_13c892_idx'),
        ),
        migrations.AddIndex(
            model_name='rawtransaction',
            index=models.Index(fields=['tx_signature'], name='warehouse_r_tx_sign_e76af3_idx'),
        ),
        # ---------------------------------------------------------------
        # RawTransaction: constraints (1 unique + 8 check)
        # ---------------------------------------------------------------
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.UniqueConstraint(fields=('coin', 'tx_signature'), name='rd001_unique_tx_per_coin'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('token_amount__gt', 0)), name='rd001_token_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('sol_amount__gte', 0)), name='rd001_sol_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('trade_type__in', ['BUY', 'SELL'])), name='rd001_trade_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('pool_token_reserves__gte', 0)), name='rd001_pool_token_reserves_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('pool_sol_reserves__gte', 0)), name='rd001_pool_sol_reserves_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('lp_fee__gte', 0)), name='rd001_lp_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('protocol_fee__gte', 0)), name='rd001_protocol_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='rawtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('coin_creator_fee__gte', 0)), name='rd001_coin_creator_fee_non_negative'),
        ),
        # ---------------------------------------------------------------
        # SkippedTransaction: new model
        # ---------------------------------------------------------------
        migrations.CreateModel(
            name='SkippedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_signature', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skipped_transactions', to='warehouse.migratedcoin', to_field='mint_address')),
                ('pool_address', models.CharField(max_length=64)),
                ('tx_type', models.CharField(max_length=64)),
                ('tx_status', models.CharField(max_length=32)),
                ('skip_reason', models.CharField(choices=[('no_trade_event', 'No Trade Event'), ('failed', 'Failed Transaction'), ('parse_error', 'Parse Error')], max_length=32)),
                ('raw_json', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(fields=('coin', 'tx_signature'), name='rd001_skipped_unique_tx_per_coin'),
                ],
            },
        ),
    ]
