# Generated by Django 6.0.3 on 2026-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_rd001_raw_transaction_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransaction',
            name='pool_sol_reserves',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransaction',
            name='pool_token_reserves',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
