# Generated by Django 6.0.3 on 2026-03-23 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_rd001_nullable_pool_reserves'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_event', models.DateTimeField(blank=True, help_text='The reference point (T0) for this asset. Populated for event-driven universes. Null for calendar-driven universes.', null=True)),
                ('membership_end', models.DateTimeField(blank=True, help_text='When this asset left the universe. Null = still a member.', null=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(max_length=10)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U002PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=20)),
                ('mode', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('steady_state', 'Steady State'), ('refill', 'Re-fill')], max_length=20)),
                ('status', models.CharField(choices=[('started', 'Started'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_expected', models.IntegerField(blank=True, null=True)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cu_consumed', models.IntegerField(default=0)),
                ('api_calls', models.IntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='warehouse.binanceasset', to_field='symbol')),
                ('batch', models.ForeignKey(blank=True, help_text='Parent batch. Null for manual one-off runs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_runs', to='warehouse.pipelinebatchrun')),
            ],
        ),
        migrations.CreateModel(
            name='U002PipelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('partial', 'Partial'), ('window_complete', 'Window Complete'), ('error', 'Error')], default='not_started', max_length=20)),
                ('watermark', models.DateTimeField(blank=True, help_text='Cached watermark — latest timestamp in the feature layer table for this entity. Source of truth is the feature layer table itself. Updated after each successful run.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, help_text='Error message from the last failed run. Null if last run succeeded.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_statuses', to='warehouse.binanceasset', to_field='symbol')),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.u002pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='U002FundingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.')),
                ('funding_interval_hours', models.IntegerField(null=True)),
                ('last_funding_rate', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rates', to='warehouse.binanceasset', to_field='symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='warehouse_u_timesta_b58480_idx'), models.Index(fields=['asset', '-timestamp'], name='idx_u002funding_asset_ts')],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='U002FuturesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.')),
                ('sum_open_interest', models.DecimalField(decimal_places=10, help_text='Total OI in base asset', max_digits=20, null=True)),
                ('sum_open_interest_value', models.DecimalField(decimal_places=10, help_text='Total OI in USDT', max_digits=24, null=True)),
                ('count_toptrader_long_short_ratio', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('sum_toptrader_long_short_ratio', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('count_long_short_ratio', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('sum_taker_long_short_vol_ratio', models.DecimalField(decimal_places=8, max_digits=12, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futures_metrics', to='warehouse.binanceasset', to_field='symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='warehouse_u_timesta_4c7dc3_idx'), models.Index(fields=['asset', '-timestamp'], name='idx_u002metrics_asset_ts')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sum_open_interest__gte', 0)), name='u002_metrics_oi_non_neg'), models.CheckConstraint(condition=models.Q(('sum_open_interest_value__gte', 0)), name='u002_metrics_oi_val_non_neg')],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='U002OHLCVCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.')),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('quote_volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('trade_count', models.IntegerField(null=True)),
                ('taker_buy_volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('taker_buy_quote_volume', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ohlcv_candles', to='warehouse.binanceasset', to_field='symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='warehouse_u_timesta_d0ffb5_idx'), models.Index(fields=['asset', '-timestamp'], name='idx_u002ohlcv_asset_ts')],
                'constraints': [models.CheckConstraint(condition=models.Q(('high_price__gte', models.F('low_price'))), name='u002_ohlcv_high_gte_low'), models.CheckConstraint(condition=models.Q(('volume__gte', 0)), name='u002_ohlcv_volume_non_neg'), models.CheckConstraint(condition=models.Q(('quote_volume__gte', 0)), name='u002_ohlcv_quote_vol_non_neg'), models.CheckConstraint(condition=models.Q(('taker_buy_volume__lte', models.F('volume'))), name='u002_ohlcv_taker_lte_vol')],
                'unique_together': {('asset', 'timestamp')},
            },
        ),
        migrations.AddIndex(
            model_name='u002pipelinerun',
            index=models.Index(fields=['asset', 'layer_id', '-started_at'], name='idx_u002run_asset_layer'),
        ),
        migrations.AddIndex(
            model_name='u002pipelinerun',
            index=models.Index(fields=['-started_at'], name='idx_u002run_started'),
        ),
        migrations.AddIndex(
            model_name='u002pipelinerun',
            index=models.Index(fields=['status'], name='idx_u002run_status'),
        ),
        migrations.AddIndex(
            model_name='u002pipelinestatus',
            index=models.Index(fields=['status'], name='idx_u002status_status'),
        ),
        migrations.AddIndex(
            model_name='u002pipelinestatus',
            index=models.Index(fields=['layer_id', 'status'], name='idx_u002status_layer_status'),
        ),
        migrations.AlterUniqueTogether(
            name='u002pipelinestatus',
            unique_together={('asset', 'layer_id')},
        ),
    ]
