# Generated by Django 6.0.3 on 2026-03-23 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_binanceasset_u002pipelinerun_u002pipelinestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='U002OrderBookSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Observation timestamp, UTC. Whether this represents interval start or end is defined by WDP9.')),
                ('side', models.CharField(choices=[('bid', 'bid'), ('ask', 'ask')], max_length=3)),
                ('level', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('last_update_id', models.BigIntegerField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book_snapshots', to='warehouse.binanceasset', to_field='symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='warehouse_u_timesta_41e8f1_idx'), models.Index(fields=['asset', '-timestamp'], name='idx_u002ob_asset_ts')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='u002_ob_qty_non_neg'), models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='u002_ob_price_positive')],
                'unique_together': {('asset', 'timestamp', 'side', 'level')},
            },
        ),
    ]
