# Generated by Django 6.0.3 on 2026-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_u002orderbooksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001OpsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('discovered_count', models.IntegerField(default=0)),
                ('mapped_count', models.IntegerField(default=0)),
                ('fl001_complete_count', models.IntegerField(default=0)),
                ('fl002_complete_count', models.IntegerField(default=0)),
                ('rd001_complete_count', models.IntegerField(default=0)),
                ('rd001_partial_count', models.IntegerField(default=0)),
                ('rd001_error_count', models.IntegerField(default=0)),
                ('rd001_transport_error_count', models.IntegerField(default=0)),
                ('rd001_guard_error_count', models.IntegerField(default=0)),
                ('fl002_auth_error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
