# Generated by Django 6.0.3 on 2026-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_u001opssnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001AutomationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='u001', max_length=20, unique=True)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('last_action', models.CharField(blank=True, max_length=64, null=True)),
                ('last_action_reason', models.TextField(blank=True, null=True)),
                ('last_action_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_action_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_action_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_snapshot_date', models.DateField(blank=True, null=True)),
                ('guarded_attempts_date', models.DateField(blank=True, null=True)),
                ('guarded_attempts_today', models.PositiveSmallIntegerField(default=0)),
                ('error_lane_tick_counter', models.PositiveIntegerField(default=0)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['singleton_key'],
            },
        ),
    ]
