# Generated by Django 6.0.3 on 2026-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_u001automationstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001AutomationTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('command', models.CharField(blank=True, max_length=64, null=True)),
                ('command_kwargs', models.JSONField(blank=True, default=dict)),
                ('repaired_state', models.BooleanField(default=False)),
                ('snapshot_taken', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [
                    models.Index(fields=['started_at'], name='warehouse_u0_started_56f5c8_idx'),
                    models.Index(fields=['action', 'status'], name='warehouse_u0_action__ef8dc3_idx'),
                ],
            },
        ),
    ]
