# Generated by Django 6.0.3 on 2026-04-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_u001automationtick'),
    ]

    operations = [
        migrations.CreateModel(
            name='U001SourceAuditRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('finding_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='u001automationtick',
            new_name='u001autotick_started_idx',
            old_name='warehouse_u0_started_56f5c8_idx',
        ),
        migrations.RenameIndex(
            model_name='u001automationtick',
            new_name='u001autotick_action_status',
            old_name='warehouse_u0_action__ef8dc3_idx',
        ),
        migrations.AddIndex(
            model_name='u001sourceauditrun',
            index=models.Index(fields=['started_at'], name='u001srcaudit_started_idx'),
        ),
        migrations.AddIndex(
            model_name='u001sourceauditrun',
            index=models.Index(fields=['status'], name='u001srcaudit_status_idx'),
        ),
    ]
